# Generated by Django 4.0.5 on 2023-09-23 12:11

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('level', models.CharField(choices=[('SMP', 'smp'), ('SMA', 'sma'), ('UMUM', 'Umum')], default='SMP', max_length=50, verbose_name='Level yang dipilih')),
                ('fee_type', models.CharField(choices=[('PF', 'Per Person Fee'), ('TF', 'Per Team Fee')], default='TF', max_length=20, verbose_name='Fee Type')),
                ('School_type', models.CharField(choices=[('PS', 'Per Person School'), ('TS', 'Per Team School')], default='TS', max_length=30, verbose_name='School Type')),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='Online', max_length=7, verbose_name='Status yang dipilih')),
                ('Pas_Foto', models.BooleanField(default=True)),
                ('Identitas', models.BooleanField(default=True)),
                ('Akte_Lahir', models.BooleanField(default=True)),
                ('Surat_Sekolah', models.BooleanField(default=True)),
                ('Teacher', models.BooleanField(default=True)),
                ('Teacher_Number', models.BooleanField(default=False)),
                ('Teacher_Photo', models.BooleanField(default=False)),
                ('Nomor_Peserta', models.BooleanField(default=False)),
                ('Surat_Izin_Orangtua', models.BooleanField(default=False)),
                ('Surat_Penanggung_Resiko', models.BooleanField(default=False)),
                ('Regi_Fee', models.PositiveIntegerField()),
                ('WO_Fee', models.PositiveIntegerField()),
                ('Minimum_Age', models.PositiveIntegerField(default=0)),
                ('Maximum_Age', models.PositiveIntegerField(default=99)),
                ('Minimum_Team_Size', models.PositiveIntegerField(default=0)),
                ('Maximum_Team_Size', models.PositiveIntegerField(default=20)),
                ('Peraturan', models.TextField(blank=True, null=True)),
                ('Official_Member', models.PositiveIntegerField(default=0)),
                ('Kuota_Team', models.PositiveIntegerField(default=200)),
                ('Contact_Person', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UP', 'UNPAID'), ('AP', 'AWAITING PAYMENT'), ('PA', 'PAID'), ('AR', 'AWAITING REVIEW'), ('ED', 'EXTRA DATA ARE NEEDED'), ('RE', 'REJECTED'), ('AC', 'ACCEPTED')], default='UP', max_length=2)),
                ('Team_Name', models.CharField(blank=True, max_length=200)),
                ('School', models.CharField(blank=True, max_length=200)),
                ('Members', models.IntegerField(blank=True)),
                ('Email', models.EmailField(max_length=300, null=True)),
                ('Surat_Sekolah', models.FileField(blank=True, upload_to=api.models.upload_to3)),
                ('Team_Code', models.CharField(default='', max_length=12)),
                ('Nomor_Rekening', models.CharField(default='', max_length=150)),
                ('Post_Token', models.CharField(default=api.models.generate_secrets_token, editable=False, max_length=128)),
                ('Competition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='api.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('Foto', models.FileField(blank=True, upload_to=api.models.upload_to4)),
                ('team', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_level', models.CharField(choices=[('TE', 'TEAM'), ('PA', 'PARTICIPANT')], max_length=4)),
                ('field_name', models.CharField(max_length=64)),
                ('choices', models.CharField(max_length=256)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field', to='api.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('birthdate', models.DateField(blank=True)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('School', models.CharField(blank=True, max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('post_token', models.CharField(blank=True, max_length=128)),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Participant', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_sum', models.PositiveIntegerField(null=True)),
                ('invoice_code', models.CharField(default='', max_length=8)),
                ('detail', models.TextField(blank=True, null=True)),
                ('transaction_details', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=255)),
                ('akte_lahir', models.FileField(blank=True, upload_to=api.models.upload_to1)),
                ('pas_foto', models.FileField(blank=True, upload_to=api.models.upload_to)),
                ('Kartu_Identitas', models.FileField(blank=True, upload_to=api.models.upload_to2)),
                ('Surat_Izin_Orangtua', models.FileField(blank=True, upload_to=api.models.upload_to6)),
                ('Surat_Penanggung_Resiko', models.FileField(blank=True, upload_to=api.models.upload_to7)),
                ('verified', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.participant')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrationcustomfield')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.participant')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
